### PR TITLE
fix lintian error 'pre-depends-directly-on-multiarch-support'

### PR DESCRIPTION
**Pull request by andhe**
This reverts commit 9def66386194a51b612990a14bf2567a035c71a7.

The multiarch-support transition is already over. Directly pre-depending
on the package rather than using the ${misc:Pre-Depends} variable
is frowned upon. Just drop Pre-Depends now that the variable will
expand to empty anyway.

This fixes lintian error 'pre-depends-directly-on-multiarch-support'

### CODE REVIEW

**Comment by andhe** [comment]
https://lists.debian.org/debian-devel/2017/07/msg00022.html

**Comment by andhe** [comment]
Oh, aurel32 has even reported a debian bug report for this (you should add Closes: #.... statement to debian/changelog for your next upload):

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=870536

**Comment by mochrul** [comment]
eventlog is merged (back) into syslog-ng and therefore I'm not sure it is worth to keep this in the archive. I expect no upstream activity and nothing is depending on eventlog except the syslog-ng.

I'm currently working on upgrading the syslog-ng to 3.11.1 and after that abandoning this.

**Comment by andhe** [comment]
Thanks for the quick feedback.

Once you're done upgrading syslog-ng, then please file a debian removal (RM) bug report for eventlog.
reportbug ftp.debian.org -> 6 (ROM) -> package: eventlog -> <enter> -> reason: merged into syslog-ng

**Pull request closed without merging**
